// Injects a `release` signingConfig into the generated android/app/build.gradle,
// reading the keystore path + passwords from environment variables that CI
// populates from GitHub Secrets. `android/` is git-ignored and regenerated by
// `expo prebuild` on every build, so this can't just be a hand-edited file —
// it has to be re-applied as a config plugin every time. Plain CommonJS (not
// TypeScript): Expo's local-plugin loader `require()`s this file directly
// without a build step.
const { withAppBuildGradle } = require('@expo/config-plugins');

const RELEASE_SIGNING_CONFIG_BLOCK = `        release {
            storeFile file(System.getenv("ANDROID_RELEASE_KEYSTORE_PATH") ?: "release.keystore")
            storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
            keyAlias System.getenv("ANDROID_KEY_ALIAS")
            keyPassword System.getenv("ANDROID_KEY_PASSWORD")
        }
        debug {`;

function patchBuildGradle(contents) {
  if (contents.includes('ANDROID_RELEASE_KEYSTORE_PATH')) {
    return contents; // already patched — keep prebuild idempotent
  }

  let patched = contents.replace(
    /signingConfigs \{\n {8}debug \{/,
    () => `signingConfigs {\n${RELEASE_SIGNING_CONFIG_BLOCK}`,
  );

  patched = patched.replace(
    /release \{\n(\s*)\/\/ Caution! In production, you need to generate your own keystore file\.\n(\s*)\/\/ see https:\/\/reactnative\.dev\/docs\/signed-apk-android\.\n(\s*)signingConfig signingConfigs\.debug/,
    (_match, indent1, _indent2, indent3) =>
      `release {\n${indent1}// Signed with the release keystore injected by CI (plugins/withReleaseSigning.js).\n${indent3}signingConfig signingConfigs.release`,
  );

  return patched;
}

function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    config.modResults.contents = patchBuildGradle(config.modResults.contents);
    return config;
  });
}

module.exports = withReleaseSigning;
module.exports.patchBuildGradle = patchBuildGradle;
