// Raises the Gradle daemon's JVM heap/metaspace above Expo's generated
// defaults (`-Xmx2048m -XX:MaxMetaspaceSize=512m`). The release build runs
// Android Lint's "vital" analysis across every native module as part of
// `assembleRelease`; with 20+ modules (Reanimated, Nitro modules, etc.) the
// default 512m metaspace reliably exhausts, and — worse — the crash leaves
// the Gradle daemon's lifecycle listener in a state where it never reports
// the failure back to the calling process, hanging the CI job indefinitely
// instead of just failing fast. `android/` is git-ignored and regenerated by
// `expo prebuild` on every build, so this has to be a config plugin, not a
// hand-edited gradle.properties.
const { withGradleProperties } = require('@expo/config-plugins');

const JVM_ARGS_KEY = 'org.gradle.jvmargs';
const JVM_ARGS_VALUE = '-Xmx4096m -XX:MaxMetaspaceSize=1024m';

function withGradleMemory(config) {
  return withGradleProperties(config, (config) => {
    const existing = config.modResults.find(
      (item) => item.type === 'property' && item.key === JVM_ARGS_KEY,
    );

    if (existing) {
      existing.value = JVM_ARGS_VALUE;
    } else {
      config.modResults.push({ type: 'property', key: JVM_ARGS_KEY, value: JVM_ARGS_VALUE });
    }

    return config;
  });
}

module.exports = withGradleMemory;
