/// <reference types="expo/types" />

// NOTE: This file is generated by Expo (`expo start`) and pulls in ambient type
// declarations for assets, CSS/CSS-modules, and env. It is committed so that
// `tsc --noEmit` passes in CI before the app has been booted locally.
